services:
  - type: web
    name: fastapi-urdu-voice
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TTS_API_KEY
        sync: false
      - key: TTS_VOICE_ID
        sync: false
